
requestFileSystem(".") {
  // Read the public changelog normally
  val changelog = access("projects/webapp/docs/changelog.md").read()

  // Read the classified incident report safely
  val incidentClassified = access("secrets/docs/incident-report.md").readClassified()

  // Build a classified prompt combining both documents
  val prompt: Classified[String] = incidentClassified.map { incident =>
    s"""You are a security analyst. Below are two documents:

=== PUBLIC CHANGELOG (projects/webapp/docs/changelog.md) ===
$changelog

=== CLASSIFIED INCIDENT REPORT (secrets/docs/incident-report.md) ===
$incident

Task:
Carefully read both documents. For each changelog release entry, assess whether it could be related to the incident described in the report. Consider:
- Timing: Does the release date align with or precede the incident?
- Scope: Do any changed components, dependencies, or features overlap with the affected systems or attack vectors in the incident?
- Risk signals: Do any bug fixes, security patches, configuration changes, or dependency updates correlate with the incident's root cause or symptoms?

Produce a structured analysis with the following sections:
1. Incident Summary (brief, 3-5 sentences)
2. Changelog Overview (brief summary of releases covered)
3. Release-by-Release Analysis (for each release: version/date, brief description, relationship to incident — "Related", "Possibly Related", or "Not Related" — with justification)
4. Key Findings (the most significant correlations or red flags)
5. Recommendations (actionable next steps based on the analysis)

Be thorough, specific, and reference exact version numbers, dates, and details from both documents."""
  }

  // Run the analysis entirely within classified context
  val analysisClassified: Classified[String] = chat(prompt)

  // Prepend a header inside the classified context
  val outputClassified: Classified[String] = analysisClassified.map { analysis =>
    s"""CLASSIFIED — INCIDENT / CHANGELOG CORRELATION ANALYSIS
Generated by automated security analysis pipeline
========================================================

$analysis

========================================================
END OF CLASSIFIED ANALYSIS
"""
  }

  // Write the result to the classified output file
  writeClassified("secrets/docs/incident-changelog-analysis.txt", outputClassified)

  println("Analysis complete. Written to secrets/docs/incident-changelog-analysis.txt")
}
