
// Read public README from the projects subtree
val readme = requestFileSystem("projects") {
  access("projects/webapp/docs/README.md").read()
}

// Read incident report and write recommendations within the secrets subtree (classified scope)
requestFileSystem("secrets") {
  val incident = access("secrets/docs/incident-report.md").read()

  // Classify the combined prompt so it never leaks to stdout
  val classifiedPrompt: Classified[String] = classify(
    s"""You are a security engineer. Based on the two documents below, produce a thorough, structured set of security recommendations for the webapp.
Format the output as a plain-text document with a title and numbered sections. Do NOT reproduce raw secrets, credentials, passwords, internal hostnames, or IP addresses anywhere in the output.

--- PUBLIC README ---
$readme

--- CLASSIFIED INCIDENT REPORT ---
$incident

Write security recommendations that directly address:
1. Findings from the incident report (credential hygiene, access control, monitoring, data protection, etc.)
2. Gaps visible in the README (missing auth, no input validation, in-memory storage, no pagination, etc.)
3. General best practices relevant to this webapp.

Structure the document with exactly these sections:
1. Executive Summary
2. Credential & Secrets Management
3. Access Control & Authentication
4. Input Validation & API Security
5. Database & Data Protection
6. Monitoring & Incident Response
7. Secure Development Practices
8. Prioritized Action Plan (Critical / High / Medium / Low)

Be specific and actionable. Reference the incident where relevant, but never disclose raw sensitive values."""
  )

  // LLM call — response stays Classified
  val classifiedRecs: Classified[String] = chat(classifiedPrompt)

  // Prepend classification header
  val classifiedFinal: Classified[String] = classifiedRecs.map { recs =>
    s"""CLASSIFICATION: CONFIDENTIAL — INTERNAL USE ONLY
Generated by: Security Review Assistant
Source inputs: projects/webapp/docs/README.md + secrets/docs/incident-report.md (IR-2024-0042)
========================================================

$recs

========================================================
END OF DOCUMENT — CONFIDENTIAL
"""
  }

  // Write securely
  val outFile = access("secrets/docs/security-recommendations.txt")
  outFile.writeClassified(classifiedFinal)

  println(s"Successfully written to: ${outFile.path}  (exists=${outFile.exists}, size=${outFile.size} bytes)")
}
