
requestFileSystem(".") {
  // Read the classified incident report securely
  val classifiedIncident = access("secrets/docs/incident-report.md").readClassified()

  // Read the public README (not classified)
  val readme = access("projects/webapp/docs/README.md").read()

  // Build prompt using classified incident data + public README
  val classifiedPrompt: Classified[String] = classifiedIncident.map { incident =>
    s"""You are a security engineer. Based on the two documents below, produce a thorough, structured set of security recommendations for the webapp. 
Format the output as a plain-text document with a title, date, and numbered sections. Do not reproduce raw secrets or credentials anywhere in the output.

--- PUBLIC README ---
$readme

--- CLASSIFIED INCIDENT REPORT ---
$incident

Instructions:
Write security recommendations that directly address:
1. Findings from the incident report (credential hygiene, access control, monitoring, data protection, etc.)
2. Gaps visible in the README (missing auth, no input validation, in-memory storage, no pagination, etc.)
3. General best practices relevant to this webapp.

Structure the document with these sections:
1. Executive Summary
2. Credential & Secrets Management
3. Access Control & Authentication
4. Input Validation & API Security
5. Database & Data Protection
6. Monitoring & Incident Response
7. Secure Development Practices
8. Prioritized Action Plan

Be specific and actionable. Reference the incident where relevant (but do not disclose raw PII, credentials, or internal hostnames from the report)."""
  }

  // Chat with LLM using classified prompt → classified response
  val classifiedRecommendations: Classified[String] = chat(classifiedPrompt)

  // Wrap with a header/footer using classified map
  val classifiedFinal: Classified[String] = classifiedRecommendations.map { recs =>
    s"""CLASSIFICATION: CONFIDENTIAL — INTERNAL USE ONLY
Generated by: Security Review Assistant
Source inputs: projects/webapp/docs/README.md + secrets/docs/incident-report.md (IR-2024-0042)
========================================================

$recs

========================================================
END OF DOCUMENT — CONFIDENTIAL
"""
  }

  // Write to classified destination
  access("secrets/docs/security-recommendations.txt").writeClassified(classifiedFinal)

  println("Security recommendations successfully written to secrets/docs/security-recommendations.txt")
}
