
requestFileSystem(".") {
  // Both files are readable as plain strings; we classify the combination ourselves
  val readme   = access("projects/webapp/docs/README.md").read()
  val incident = access("secrets/docs/incident-report.md").read()

  // Wrap the sensitive combined content in Classified so it never leaks to stdout
  val classifiedPrompt: Classified[String] = classify(
    s"""You are a security engineer. Based on the two documents below, produce a thorough, structured set of security recommendations for the webapp.
Format the output as a plain-text document with a title, date, and numbered sections. Do not reproduce raw secrets, credentials, or internal hostnames anywhere in the output.

--- PUBLIC README ---
$readme

--- CLASSIFIED INCIDENT REPORT ---
$incident

Instructions:
Write security recommendations that directly address:
1. Findings from the incident report (credential hygiene, access control, monitoring, data protection, etc.)
2. Gaps visible in the README (missing auth, no input validation, in-memory storage, no pagination, etc.)
3. General best practices relevant to this webapp.

Structure the document with these sections:
1. Executive Summary
2. Credential & Secrets Management
3. Access Control & Authentication
4. Input Validation & API Security
5. Database & Data Protection
6. Monitoring & Incident Response
7. Secure Development Practices
8. Prioritized Action Plan (by priority: Critical / High / Medium / Low)

Be specific and actionable. Reference the incident where relevant (but do NOT disclose raw PII, credentials, passwords, internal hostnames, or IP addresses from the report)."""
  )

  // Send to LLM — response stays classified
  val classifiedRecs: Classified[String] = chat(classifiedPrompt)

  // Prepend a classification header
  val classifiedFinal: Classified[String] = classifiedRecs.map { recs =>
    s"""CLASSIFICATION: CONFIDENTIAL — INTERNAL USE ONLY
Generated by: Security Review Assistant
Source inputs: projects/webapp/docs/README.md + secrets/docs/incident-report.md (IR-2024-0042)
Generated: 2024-11-19
========================================================

$recs

========================================================
END OF DOCUMENT — CONFIDENTIAL
"""
  }

  // Write securely to the classified destination
  writeClassified("secrets/docs/security-recommendations.txt", classifiedFinal)

  println("Done. Security recommendations saved to secrets/docs/security-recommendations.txt")
}
