
requestFileSystem(".") {
  // Read public changelog normally
  val changelog: String = access("projects/webapp/docs/changelog.md").read()

  // Read classified incident report safely
  val incidentClassified: Classified[String] = access("secrets/docs/incident-report.md").readClassified()

  // Build a classified LLM prompt combining both documents
  val prompt: Classified[String] = incidentClassified.map { incident =>
    s"""You are a security analyst. You have been given two documents:

=== PUBLIC CHANGELOG ===
$changelog

=== CLASSIFIED INCIDENT REPORT ===
$incident

=== YOUR TASK ===
Analyze whether any changelog releases are related to or may have contributed to the incident described in the report.

For each potentially related release, explain:
1. The release version and date.
2. The specific change(s) in that release that may be relevant.
3. The nature of the relationship (e.g., introduced a vulnerability, deployed a faulty fix, changed behaviour that triggered the incident, etc.).
4. Your confidence level (High / Medium / Low) and reasoning.

Finally, write a short executive summary (3-5 sentences) describing the overall connection between the changelog and the incident.

Format the output clearly with headings. Be thorough and precise."""
  }

  // Call the LLM with the classified prompt → classified response
  val analysisClassified: Classified[String] = chat(prompt)

  // Wrap with a header/footer, still classified
  val finalClassified: Classified[String] = analysisClassified.map { analysis =>
    s"""INCIDENT-CHANGELOG ANALYSIS
============================
Classification: SECRET
Generated by: Automated Security Analysis Pipeline

$analysis

--- END OF ANALYSIS ---"""
  }

  // Write to the classified output file
  access("secrets/docs/incident-changelog-analysis.txt").writeClassified(finalClassified)

  println("Analysis complete. Written to secrets/docs/incident-changelog-analysis.txt")
}
