
requestFileSystem(".") {
  // Read the public changelog (unclassified)
  val changelog = access("projects/webapp/docs/changelog.md").read()

  // Read the classified incident report safely
  val incidentClassified: Classified[String] = access("secrets/docs/incident-report.md").readClassified()

  // Build a classified prompt combining both sources
  val prompt: Classified[String] = incidentClassified.map { incident =>
    s"""You are a security analyst. You have been given two documents:

=== PUBLIC CHANGELOG (projects/webapp/docs/changelog.md) ===
$changelog

=== CLASSIFIED INCIDENT REPORT (secrets/docs/incident-report.md) ===
$incident

Task:
Analyze whether any of the changelog releases might be related to — or could have caused, contributed to, or coincided with — the incident described in the incident report.

Your analysis should:
1. Summarize the key facts of the incident (timeline, affected systems, nature of the issue).
2. Identify each changelog release that is potentially related, with specific reasoning for each.
3. Flag the most likely culprit release(s) if any, and explain why.
4. Note any releases that are definitively unrelated and why.
5. Provide a conclusion with an overall assessment.

Write the analysis in a clear, structured report format suitable for a security review."""
  }

  // Run the analysis via the classified LLM channel
  val analysisClassified: Classified[String] = chat(prompt)

  // Wrap in a final classified document
  val outputClassified: Classified[String] = analysisClassified.map { analysis =>
    s"""INCIDENT–CHANGELOG CROSS-ANALYSIS REPORT
Generated by: Automated Security Analysis
Classification: CLASSIFIED
========================================

$analysis
"""
  }

  // Write the result to the classified output file
  access("secrets/docs/incident-changelog-analysis.txt").writeClassified(outputClassified)

  println("Analysis complete. Written to secrets/docs/incident-changelog-analysis.txt")
}
