
requestFileSystem(".") {
  // Read the public changelog normally
  val changelog = access("projects/webapp/docs/changelog.md").read()

  // Read the classified incident report securely
  val incidentClassified = access("secrets/docs/incident-report.md").readClassified()

  // Build a classified analysis prompt combining both documents
  val prompt: Classified[String] = incidentClassified.map { incidentText =>
    s"""You are a security and release analyst. Below are two documents:

=== PUBLIC CHANGELOG ===
$changelog

=== CLASSIFIED INCIDENT REPORT ===
$incidentText

Task: Carefully cross-reference the changelog releases against the incident report. Identify:
1. Which release(s) are most likely related to the incident, and why (timing, feature overlap, bug fixes, authors, components, etc.).
2. Any suspicious patterns across releases leading up to or following the incident.
3. Specific changelog entries (version numbers, dates, descriptions) that correlate with incident details.
4. An overall risk assessment and recommended follow-up actions.

Write a structured, detailed analysis report suitable for a security team. Be specific — quote or reference exact version numbers and changelog entries where relevant."""
  }

  // Send the classified prompt to the LLM and get a classified response
  val analysisClassified: Classified[String] = chat(prompt)

  // Prepend a classified header and save to the classified output file
  val outputClassified: Classified[String] = analysisClassified.map { analysis =>
    s"""INCIDENT–CHANGELOG CROSS-REFERENCE ANALYSIS
============================================
Generated by: Automated Security Analyst
Classification: CLASSIFIED

$analysis
"""
  }

  writeClassified("secrets/docs/incident-changelog-analysis.txt", outputClassified)
  println("✅ Analysis written to secrets/docs/incident-changelog-analysis.txt")
}
